const mongoose = require('mongoose');
const faker = require('faker');
mongoose.connect('mongodb://victor:victor123@ds125385.mlab.com:25385/products');

const db = mongoose.connection;

db.on('error', console.error.bind(console, 'connection error:'));
db.once('open', function() {
  console.log('Connection is open')
});

//define my Schema
const Schema = mongoose.Schema;

const reviewSchema = new Schema({
  product_id: Number,
  category: String,
  product_name: String,
  product_ratings: Number,
  review: String,
  review_title: String,
  reviewer: String,
  images: [],
  verified_purchase: Boolean,
  helpful_counter: Number,
  created_at: String
})

//Compile a model Review from the Schema
let Review = mongoose.model('Review', reviewSchema);
//'Review' is the model


var data1 = {
  "product_id": [],
  "category": ['shoes', 'electronics', 'apparel', 'auto', 'health', 'lifestyle', 'tech', 'furniture', 'splurge', 'food'],
  "product_name": [],
  "product_ratings": [],
  "reviewer": [],
  "review_title": [],
  "review": [],
  "images": [],
  "verified_purchase": [true, false],
  "helpful_counter": [],
  "created_at": []
}

var data = { product_id: 
  [ 1,
      2,
      3,
      4,
      5,
      6,
      7,
      8,
      9,
      10,
      11,
      12,
      13,
      14,
      15,
      16,
      17,
      18,
      19,
      20,
      21,
      22,
      23,
      24,
      25,
      26,
      27,
      28,
      29,
      30,
      31,
      32,
      33,
      34,
      35,
      36,
      37,
      38,
      39,
      40,
      41,
      42,
      43,
      44,
      45,
      46,
      47,
      48,
      49,
      50,
      51,
      52,
      53,
      54,
      55,
      56,
      57,
      58,
      59,
      60,
      61,
      62,
      63,
      64,
      65,
      66,
      67,
      68,
      69,
      70,
      71,
      72,
      73,
      74,
      75,
      76,
      77,
      78,
      79,
      80,
      81,
      82,
      83,
      84,
      85,
      86,
      87,
      88,
      89,
      90,
      91,
      92,
      93,
      94,
      95,
      96,
      97,
      98,
      99,
      100 ],
   category: 
    [ 'shoes',
      'electronics',
      'apparel',
      'auto',
      'health',
      'lifestyle',
      'tech',
      'furniture',
      'splurge',
      'food' ],
   product_name: 
    [ 'Gorgeous Wooden Mouse',
      'Awesome Plastic Keyboard',
      'Intelligent Steel Ball',
      'Fantastic Plastic Gloves',
      'Incredible Soft Gloves',
      'Intelligent Wooden Hat',
      'Incredible Granite Shirt',
      'Small Frozen Chips',
      'Handmade Granite Pants',
      'Incredible Cotton Fish',
      'Handcrafted Fresh Towels',
      'Handmade Metal Computer',
      'Generic Fresh Salad',
      'Intelligent Steel Bacon',
      'Generic Metal Chair',
      'Licensed Rubber Tuna',
      'Handmade Plastic Shoes',
      'Incredible Frozen Car',
      'Refined Plastic Bacon',
      'Ergonomic Soft Soap',
      'Handcrafted Metal Computer',
      'Unbranded Fresh Cheese',
      'Tasty Granite Towels',
      'Handcrafted Rubber Table',
      'Refined Rubber Chicken',
      'Refined Concrete Shoes',
      'Generic Soft Sausages',
      'Licensed Wooden Pizza',
      'Gorgeous Rubber Salad',
      'Intelligent Steel Chicken',
      'Intelligent Metal Fish',
      'Intelligent Soft Towels',
      'Incredible Fresh Soap',
      'Fantastic Granite Chips',
      'Handcrafted Fresh Cheese',
      'Refined Cotton Table',
      'Ergonomic Granite Ball',
      'Small Soft Hat',
      'Tasty Frozen Pants',
      'Fantastic Steel Keyboard',
      'Ergonomic Cotton Chicken',
      'Practical Plastic Tuna',
      'Awesome Soft Hat',
      'Small Granite Tuna',
      'Handcrafted Steel Chair',
      'Generic Wooden Towels',
      'Unbranded Fresh Bacon',
      'Fantastic Granite Mouse',
      'Sleek Fresh Chips',
      'Intelligent Cotton Chips',
      'Awesome Cotton Car',
      'Refined Steel Computer',
      'Practical Wooden Chips',
      'Handcrafted Frozen Bacon',
      'Rustic Cotton Towels',
      'Practical Plastic Shirt',
      'Small Plastic Pizza',
      'Small Fresh Shirt',
      'Handmade Plastic Pants',
      'Unbranded Cotton Table',
      'Practical Frozen Salad',
      'Tasty Metal Table',
      'Generic Frozen Sausages',
      'Licensed Metal Car',
      'Rustic Concrete Pizza',
      'Awesome Concrete Pizza',
      'Intelligent Metal Sausages',
      'Gorgeous Plastic Hat',
      'Small Steel Chicken',
      'Practical Rubber Fish',
      'Unbranded Frozen Chicken',
      'Intelligent Plastic Car',
      'Awesome Fresh Chips',
      'Unbranded Granite Ball',
      'Ergonomic Rubber Computer',
      'Awesome Fresh Gloves',
      'Unbranded Soft Chicken',
      'Small Fresh Keyboard',
      'Intelligent Steel Soap',
      'Sleek Cotton Chair',
      'Rustic Frozen Hat',
      'Small Wooden Soap',
      'Sleek Fresh Shirt',
      'Gorgeous Plastic Gloves',
      'Practical Soft Bacon',
      'Incredible Wooden Chair',
      'Unbranded Steel Mouse',
      'Small Fresh Pants',
      'Practical Plastic Shirt',
      'Generic Fresh Mouse',
      'Incredible Rubber Tuna',
      'Small Plastic Soap',
      'Tasty Plastic Ball',
      'Rustic Metal Shirt',
      'Small Plastic Soap',
      'Refined Concrete Cheese',
      'Handmade Wooden Pants',
      'Generic Steel Table',
      'Licensed Frozen Fish',
      'Handmade Plastic Towels' ],
   product_ratings: [ 1, 2, 3, 4, 5 ],
   reviewer: 
    [ 'Shakira Block',
      'Sherwood Gleason',
      'Darion Goldner IV',
      'Christine Rohan',
      'Ms. Damon Cole',
      'Mr. Lisandro Greenfelder',
      'Ms. Felicia Robel',
      'Mrs. Green Ledner',
      'Miss Lea Okuneva',
      'Whitney Lesch',
      'Ursula Cummings',
      'Alfredo Schmidt II',
      'Zora Crona',
      'Stephany Moen',
      'Allison Hane',
      'Cyrus Breitenberg DDS',
      'Eda Quitzon',
      'Samson Effertz',
      'Christophe Prohaska',
      'Mr. Brennon Champlin',
      'Ansel Gerhold',
      'Leora Bailey',
      'Marcos O\'Connell',
      'Pierre Hauck',
      'Oda Mertz PhD',
      'Austin Reichel',
      'Beulah Kertzmann',
      'Jasmin Brown',
      'Preston Schuppe',
      'Fiona Schuppe',
      'Mr. Adalberto Hoppe',
      'Jaden Nikolaus',
      'Lourdes Ward',
      'Randy Walsh',
      'Sedrick Adams',
      'Cathy Glover',
      'Vern O\'Hara',
      'Mr. Terrill Mann',
      'Dane Wiegand',
      'Michaela Kautzer',
      'Gilda Ortiz',
      'Marjolaine Emard',
      'Dexter Watsica',
      'Bud Rolfson IV',
      'Dr. Kay Pouros',
      'Carmel Turner',
      'Sheila Bauch',
      'Ulices Kulas',
      'Korey Doyle',
      'Issac Rohan',
      'Mr. Emmett Blanda',
      'Helmer Witting',
      'Derrick Rodriguez',
      'Raina Tillman',
      'Donna Labadie',
      'Brenna Boyer',
      'Aiyana Zieme',
      'Joel Metz',
      'Leila Barrows',
      'Haylie Farrell',
      'Mackenzie Borer',
      'Nia Goldner',
      'Cortney Kessler',
      'Mr. Maverick Abbott',
      'Kip Jones',
      'Mireya McClure',
      'Lizeth Hackett',
      'Wilfred Schowalter',
      'Ms. Jamaal Pfeffer',
      'Ms. Maryjane Nienow',
      'Aniyah Luettgen I',
      'Geo Rodriguez',
      'Owen Jenkins',
      'Kieran Ryan',
      'Euna Crist',
      'Wade Goyette',
      'Carter Crooks',
      'Gaylord Robel',
      'Norwood Rogahn',
      'Madelynn Gaylord',
      'Evangeline Schumm',
      'Dylan Kerluke',
      'Susanna Leannon',
      'Electa Greenholt',
      'Johnpaul Dickens',
      'Florian Gottlieb',
      'Abbie Mante',
      'Ms. Santiago Olson',
      'Karolann Mayer Sr.',
      'Ms. Bell Littel',
      'Caleigh Wyman',
      'Haleigh Hyatt',
      'Oswaldo Paucek',
      'Russell Schmitt',
      'Otho Bogisich DDS',
      'Sherman Ferry',
      'Dr. Kristian Crist',
      'Armand McDermott',
      'Dee Schulist',
      'Icie O\'Hara' ],
   review_title: 
    [ 'In quis non repellendus quo ut enim velit eius.',
      'Ullam dolorum enim vitae molestiae.',
      'Qui dolorem blanditiis consequatur enim tempora vitae libero corporis.',
      'Debitis iste magni reprehenderit id est qui.',
      'Quaerat earum deleniti.',
      'Eos culpa ipsum magni distinctio officia autem quos quam eum.',
      'Voluptas modi ut.',
      'Sunt nihil occaecati.',
      'Consequatur est hic.',
      'Architecto excepturi possimus atque quibusdam placeat et quis aut.',
      'Voluptatem necessitatibus quidem voluptates in perferendis consequuntur optio rem.',
      'Deleniti ea laborum provident totam dolor et quaerat quia aliquam.',
      'Ut repellat consequatur vel non.',
      'Nihil soluta voluptatem aliquid dolorem et eveniet maiores.',
      'Dolorem unde quis repudiandae sint voluptas omnis.',
      'Et magni deleniti autem.',
      'Optio sed expedita quo.',
      'Accusantium mollitia repellendus non labore ut facere quas.',
      'Debitis neque animi.',
      'Iusto quos qui aut nulla pariatur voluptate.',
      'Quia recusandae sequi deleniti nulla necessitatibus rerum occaecati.',
      'Ducimus quis unde accusamus quo quaerat.',
      'Dignissimos similique consectetur possimus ea atque ullam nobis veniam voluptatem.',
      'Ut maxime sint ex ut mollitia voluptas et.',
      'Debitis omnis aliquid at voluptatem asperiores quae veritatis.',
      'Temporibus et minima.',
      'Molestias totam ipsum illum perspiciatis accusantium.',
      'Dolorem enim porro et.',
      'Asperiores fugit sed quo tempora.',
      'Maxime fugit voluptas sapiente dicta animi ducimus laborum eaque sit.',
      'Corrupti officiis libero accusamus optio quam eaque.',
      'Saepe nesciunt provident molestiae architecto sed quis temporibus tempora officiis.',
      'Omnis explicabo quia ipsa.',
      'Ipsa quas blanditiis autem.',
      'Fugit sint facilis natus voluptate tempora molestias veniam autem.',
      'Tempora qui aperiam corrupti dolor.',
      'Pariatur fugiat possimus consectetur temporibus aspernatur asperiores deleniti omnis qui.',
      'Laboriosam aut ut porro.',
      'Non a rerum qui voluptatem.',
      'Voluptatibus recusandae officiis sint dolor dolorum et iusto.',
      'Omnis dolorem molestiae dicta inventore consequatur eum provident.',
      'Beatae ad suscipit.',
      'Dicta qui aliquam beatae consequuntur tempore cum id aut.',
      'Facere laudantium est voluptas.',
      'Atque qui facere.',
      'Est itaque explicabo.',
      'Ab repellendus consequatur et recusandae totam voluptatem in suscipit.',
      'Aperiam sed explicabo et asperiores vel.',
      'Vitae nobis quaerat id provident ea rerum.',
      'Omnis reiciendis fugiat.',
      'Autem est qui non.',
      'Ipsum est voluptatem vitae sed consequatur distinctio ipsum qui ut.',
      'Delectus dolore nesciunt quidem sapiente aut officiis omnis.',
      'Rerum iure perspiciatis quas laborum possimus pariatur iste.',
      'Ea minus sequi exercitationem porro doloribus voluptas sed.',
      'Quos non eos aut exercitationem et veniam unde.',
      'Itaque porro cumque.',
      'Aliquam ut corrupti in.',
      'Quia voluptatem nam corporis sit aut a accusantium sunt.',
      'Aperiam nihil voluptas quo eos consequatur velit consequatur alias eos.',
      'Eius unde ut nihil odit quam qui officiis.',
      'Sed aut veritatis reiciendis et distinctio non quis ea eos.',
      'Vitae numquam vel.',
      'Vel assumenda autem blanditiis tempore quia.',
      'Vitae eos autem et ab doloremque corporis ex.',
      'Atque quod illo aut.',
      'Sint ut illo totam ut ullam ut nemo nam aut.',
      'Architecto doloribus aut odit voluptatibus soluta aut.',
      'Quo labore dolor quia voluptas quaerat nam eos voluptatem possimus.',
      'Similique iure dolorem necessitatibus.',
      'Omnis facilis fugiat quos sed non.',
      'Optio ullam est aliquam hic illum.',
      'Earum dolores harum cupiditate ratione in fuga rerum placeat.',
      'Consequatur quos ea commodi qui.',
      'Soluta tempora atque corrupti.',
      'Eius iste vero architecto molestias accusantium velit voluptatem molestias aliquid.',
      'Sit non nesciunt et autem ut.',
      'Et in cum optio dignissimos reiciendis quibusdam voluptatem distinctio fugiat.',
      'Illum quidem enim.',
      'Nihil ut quidem vero doloremque exercitationem non recusandae laborum dicta.',
      'Aliquid consequatur nulla rem ut.',
      'Beatae quia qui vero doloremque ut sed.',
      'Odio odit cumque qui aut assumenda possimus debitis quisquam.',
      'Rem vitae fugit beatae aut iure.',
      'Harum ut totam rem inventore officiis ut tempora deserunt repudiandae.',
      'Rerum a est rerum quis.',
      'Molestias soluta rerum aspernatur quo nihil necessitatibus vitae.',
      'Ullam voluptatem vel reiciendis repellendus voluptas eos.',
      'Esse odit enim est omnis sed nesciunt unde et illo.',
      'Minus suscipit voluptatum aut qui blanditiis delectus deserunt voluptatem aut.',
      'Dolor dolore ea ut vel et.',
      'Est magnam totam.',
      'Aut eos ut.',
      'Numquam molestiae quisquam veniam ut quisquam ipsam fugit quo.',
      'Sed optio accusantium quidem.',
      'Eos ipsum voluptatum esse non.',
      'Neque quasi ipsam perferendis.',
      'Quae aliquid non sint.',
      'Officia numquam quod mollitia totam numquam dolor incidunt provident corporis.',
      'Earum natus id libero labore.' ],
   review: 
    [ 'Adipisci eum illo. Sit culpa porro. Provident voluptates voluptatibus reprehenderit harum. Ab perferendis laboriosam ipsum id. Cumque voluptas sit laboriosam voluptates dolorem et dolorem quia aut. Inventore nulla qui aut sed suscipit omnis.',
      'Rem non magnam neque itaque eligendi dolores ut modi in. Minus sint suscipit iusto ut quia soluta neque. Soluta atque dolorem enim eum eligendi. Iure molestias earum illum nesciunt velit fugiat possimus quas voluptas.',
      'Sint necessitatibus perspiciatis. Modi ab cumque minima nihil. Minus in non velit. Porro ratione exercitationem est molestiae voluptatem eos error iure reprehenderit.',
      'Optio in dolores illum doloribus dignissimos recusandae. Modi et occaecati ea tenetur id vitae rerum ipsam maxime. Consequatur nesciunt porro aut minus voluptatem suscipit porro numquam eum. Beatae iste nihil repellendus ipsa qui nulla.',
      'Optio repellat adipisci animi in ut. Quos totam suscipit adipisci explicabo aut reprehenderit labore. Unde vitae aliquam. Dolores ut repellendus et sunt explicabo nostrum expedita architecto iste. Repellat adipisci assumenda ut quae.',
      'Amet unde repudiandae. Reprehenderit saepe voluptate minus et sint excepturi laboriosam rem.',
      'Earum rerum repellat tenetur. Vitae in velit dolorum aperiam blanditiis consequatur. Commodi ad ut veniam voluptatem dolores id in. Illo quae quaerat. Explicabo aut vero impedit assumenda fuga id molestiae et voluptas.',
      'Harum placeat ex mollitia qui. Quia quas est eligendi eos neque.',
      'Iusto nisi pariatur itaque voluptatem dolores. Et voluptas repellendus vel nemo. Voluptatem exercitationem hic velit. Tempore odit dolorem. Fugiat dolor et et.',
      'Sunt tempore officia nihil sint velit et occaecati placeat. Quo omnis sint repellendus esse aliquid enim. Fugiat ex qui enim.',
      'Distinctio fugit quisquam id ipsa aut id quaerat. Ullam dolores voluptas ipsum voluptas qui sit totam. Dolor aspernatur quis et. Et repellat adipisci. Qui odio dolorum quam nostrum possimus. Tempora repellat ut sed itaque suscipit.',
      'Velit repellat enim praesentium quas ut. Expedita dolores minima nulla quisquam est ab dolore suscipit dignissimos. Non ut nostrum enim rerum quisquam.',
      'Minus nesciunt qui error. Ab non harum est recusandae quidem voluptatem eos. Nemo laudantium dolore voluptate autem placeat sunt. Sed repellendus quos. Et magnam quis. Consequatur ut mollitia aut.',
      'Corporis veniam sunt aliquam iure distinctio qui a molestiae. Neque earum qui.',
      'Voluptatem sit ut. Quam minima in rem. A laudantium aut laborum. Sit tenetur facere magnam nihil corporis quisquam labore.',
      'Asperiores occaecati voluptatibus sunt recusandae id ad voluptatem vero quod. Ut hic voluptate. In expedita aperiam omnis eius. Eaque ad dolorem occaecati officiis quisquam quasi.',
      'Unde cupiditate consequatur eaque expedita delectus eos deleniti molestiae. Occaecati ut eius esse enim eos impedit. Fugiat in quam odit ratione et. Et possimus enim architecto animi consectetur nam. Praesentium labore accusantium saepe fugiat repudiandae doloribus debitis natus. Explicabo eum totam ea quam consectetur eius ipsa sequi.',
      'Illo sint inventore. Voluptates deleniti ipsum quia aut recusandae est rerum veniam hic. Asperiores sit rerum iste et. Est enim et enim.',
      'Consequatur suscipit corrupti. Harum eum placeat. Illo et numquam. Consequuntur explicabo fugiat neque. Occaecati eum reprehenderit saepe rem omnis et. Illum minus blanditiis quis deleniti eum atque quasi voluptates.',
      'Aperiam tempore quis sed esse quaerat consequatur quos ipsam. Consequatur nostrum libero dolor est ipsa optio. Praesentium labore eius iure et commodi sapiente neque earum ex. Deleniti enim sint nihil quia quae natus ipsum consequatur. Molestiae optio fuga error est rerum dolorem. Possimus esse fugit est eos labore nesciunt aut.',
      'Sunt explicabo itaque fuga et sint sunt maiores. Inventore libero illum animi sit ipsum est eaque. Aut illum nisi cumque enim sit. Aut repellendus laboriosam blanditiis et ad eius sit voluptate.',
      'Nam ut ut enim numquam. Dolores labore ut. Rerum consectetur aut consectetur a repellat. Rerum natus dolore sed temporibus ullam adipisci aperiam ad.',
      'Enim provident provident possimus. Sit porro sunt quis tempore delectus assumenda voluptas in. Ullam autem exercitationem blanditiis. Debitis magnam libero et et animi. Accusamus quis cupiditate voluptatibus. Eius sunt impedit laborum dolorem perferendis eum.',
      'Id et consectetur enim amet voluptatem voluptas. Similique quisquam repudiandae explicabo officiis. Aliquid non autem odio qui nemo. Itaque necessitatibus atque laborum et qui maiores. Nam voluptatum odio modi et voluptatem quia sed.',
      'Consequatur delectus est culpa et. Ex voluptas qui at alias. Neque perspiciatis fuga laudantium ut ut. Quod tempore praesentium consequatur similique.',
      'Qui architecto molestiae et ea hic laboriosam necessitatibus. Eum natus illum. Voluptatem possimus ex autem placeat accusamus. Illo quia numquam architecto fuga amet. Fugit harum autem.',
      'Omnis saepe quod numquam. Vel et est modi. Aut hic ipsam voluptatem et sint totam laborum sint. Quis non earum voluptatem odio iusto numquam quos.',
      'Exercitationem numquam earum laboriosam vel quia debitis. At quia dicta. Atque eligendi ea aperiam vero ab tempora atque laborum eos. Suscipit qui consequatur voluptatem et adipisci in consequatur dolores.',
      'Excepturi labore placeat totam. Soluta ipsa provident et excepturi sunt ut. Mollitia dolor enim voluptatum. Vel autem aut. Sequi nostrum hic at doloremque facilis nihil eos dolorem.',
      'Fugiat quidem quibusdam alias consequuntur et et magnam vel. Ut temporibus totam laudantium sit quia. Odit eius incidunt quisquam molestiae illum enim.',
      'Voluptatem occaecati tenetur. Dolorem reiciendis ut fugit nulla non natus aliquid quibusdam. Magnam ad cupiditate officiis et eos rerum fuga aut sed.',
      'Vitae temporibus et iste. Deserunt beatae voluptate iusto repellat recusandae praesentium. Libero vel dolorum quis iure voluptate quaerat est commodi. Quisquam molestias sequi eos. Ex ea illo consequuntur voluptatibus rerum quidem nemo consequuntur non.',
      'Et nisi sit architecto possimus molestiae aut atque assumenda accusantium. Temporibus accusamus excepturi quam voluptatem labore doloribus odit quis dolore. Doloribus consequuntur ducimus veritatis velit voluptatem excepturi explicabo eius. Perferendis veritatis cupiditate et eum est.',
      'Magni saepe sed est illum. Quidem aut deleniti. Asperiores et placeat. Fugit ratione odio pariatur officiis aperiam voluptas nisi.',
      'At explicabo et quod facere dolores quas iure. Inventore vel minus qui.',
      'Aut minus sint. Praesentium vel eum voluptatem vitae. Quos esse sed sunt. Vel excepturi dolorum et reiciendis neque quas. In nisi corporis soluta eum eum voluptas vel amet vitae.',
      'Accusamus id quis expedita voluptates velit laboriosam labore. Tempore officiis quo corporis reprehenderit recusandae at placeat excepturi. Porro nihil aliquid sed totam blanditiis quam. Soluta ipsam ut quidem et praesentium odit asperiores voluptatem porro.',
      'Sapiente exercitationem iste vel quia nobis molestiae blanditiis hic. Quaerat blanditiis et in placeat. Accusantium aspernatur earum asperiores. Aliquam error distinctio voluptatum non sint qui aut et officia.',
      'Beatae corrupti deserunt enim soluta ab sit enim rem in. Est officia dolorem. Maxime quod sapiente ratione architecto quod. Pariatur pariatur omnis. Veniam quod voluptates officia repellat sit atque quos. Dolorem est quae dolor ut magnam eveniet mollitia nesciunt aspernatur.',
      'Voluptas recusandae quia voluptas itaque labore eum fugiat atque. Ex quis voluptatem totam. Velit rerum non nisi non. Ea ut autem expedita fugit dolor eaque ad et quod. Voluptatem sint aspernatur sit recusandae. Eius aut hic nemo.',
      'Nemo ipsum libero rerum. Qui dolor rerum excepturi alias alias.',
      'Cupiditate quis omnis. Quam at molestias necessitatibus corrupti voluptatum accusantium. Mollitia id quasi porro. Itaque alias sed voluptate aut.',
      'Omnis molestiae consequuntur eaque. Illo similique ut et quas blanditiis eum ratione non odio. Optio rerum quasi fugiat. Officia maiores sit consequatur officiis vel autem. Excepturi quis saepe. Ut voluptatem nihil omnis aut dolorem magnam fugiat sit beatae.',
      'Quos harum repudiandae iste occaecati dolor quasi. Est expedita sint officia excepturi deleniti. Vero est unde repudiandae quo veritatis.',
      'Culpa sunt voluptatem eum molestias officia eveniet ab vel unde. Fugiat recusandae quibusdam sint quod officia laboriosam voluptatem dolorem.',
      'Animi voluptatem ut ex sed neque. Et commodi aut ea omnis quia. Sunt numquam aliquid tenetur totam veritatis eius facilis minima.',
      'Assumenda non est facilis porro odio id ipsum. Nisi reprehenderit doloremque maiores soluta qui assumenda.',
      'Quaerat omnis assumenda omnis cumque consequatur odio accusamus. Officia ipsa rerum. Neque necessitatibus rem mollitia et nesciunt. Ab soluta architecto voluptatem voluptas. Qui quod dolorem tempora aut animi consequatur expedita. Sit laboriosam et illo eveniet velit voluptatem ratione.',
      'Accusamus maiores nulla iste aliquam id maxime est voluptas. Quae maiores laboriosam sequi veritatis ea non quidem quia. Nemo placeat accusantium voluptates reiciendis nisi voluptas officiis nihil. Nam sed distinctio pariatur distinctio et voluptatem voluptatem quod. Et eum et. Omnis vel occaecati velit.',
      'Nisi voluptas qui nihil neque. Officia ipsam animi modi.',
      'Blanditiis aut sed amet. Nihil ad qui eum blanditiis dignissimos assumenda et. Sit eveniet expedita nihil. Quia minus voluptatem facilis. Consequatur expedita non officiis. Corporis nobis doloremque iste iusto nihil.',
      'Fugiat optio enim adipisci dicta qui ad. Suscipit rem qui nostrum dicta iste non quod. Eum qui velit dolores quidem esse esse. Sint nam minima est dolore ut molestias. Ex ut dolorem sed error neque corporis ut molestias. Iste amet fugit accusamus nihil quae similique est.',
      'Cumque facere amet ea architecto quis molestias dolores. In magnam velit quibusdam a perferendis.',
      'Deleniti voluptate et iure velit quae. Qui earum dignissimos sed tempore et alias esse qui magni. Sit illum id harum nulla itaque odio cum culpa.',
      'Sit sed dignissimos cum. Quo pariatur consequuntur et.',
      'Velit quia exercitationem beatae quam vel delectus. Assumenda repellendus harum ullam repudiandae eos quam nostrum iste. Suscipit nihil voluptatibus voluptas et minima ad dicta aut amet. Repudiandae voluptatem esse inventore eligendi.',
      'Ut cum ipsam non adipisci laboriosam. Perspiciatis delectus quis facere mollitia cupiditate reprehenderit. Et totam unde eos soluta et ut similique velit. Voluptatibus alias reprehenderit consequatur. Aut velit omnis sint amet et reiciendis dolorum quod perferendis. Dignissimos quos omnis ut occaecati aliquam maxime non.',
      'Ullam eaque voluptatem numquam minima earum sint quibusdam aspernatur. Deleniti et error officia deleniti tempore et. Harum qui repudiandae eligendi et. Unde similique architecto. Et rerum ipsum aliquid ut aut deleniti ipsa.',
      'Enim dolore mollitia quo cum et ipsum. Aspernatur et numquam ut reprehenderit nihil. Et provident suscipit corporis.',
      'Consequuntur fugiat aut nisi fugit ex dolorum rerum. Eos ex vel excepturi velit molestiae et culpa.',
      'Voluptas distinctio quo ut sed voluptas harum aspernatur eum. Labore et mollitia rerum error sint id sed magnam quia. Et amet voluptatem. Cupiditate et aut amet suscipit ut est at debitis.',
      'Aliquam et est ut facere vero officia eveniet animi illo. Voluptas soluta quia at praesentium ut aliquid reiciendis nam. Autem sit voluptatem consequuntur voluptatem. Ad mollitia enim voluptates. Rerum et nihil asperiores mollitia quos dolor nobis fugiat hic. Dolorum est porro amet.',
      'Quod eaque consequuntur voluptatibus vero minus. Quo aut fugit aliquam nesciunt voluptate. Eos facere voluptatem corrupti aliquam recusandae voluptate dolor. Sint deserunt suscipit consectetur. Reiciendis consequuntur consequatur voluptatum cumque consectetur saepe ut.',
      'Autem consequatur optio. Mollitia autem aut ea. Aut itaque cupiditate commodi ut vitae ipsam earum voluptatem. Omnis nihil explicabo aut repudiandae dolorem fuga vero. Nihil magni temporibus impedit corrupti et eum qui voluptas optio.',
      'Qui laborum est inventore officiis quo fuga occaecati praesentium. Unde consequuntur iure sequi voluptatem. Molestiae voluptatem voluptas.',
      'Deserunt nisi voluptas voluptas id corporis veritatis a quas minus. Dolores molestiae recusandae. Hic aliquam expedita nisi vero. Expedita repellendus atque officia unde et enim. Omnis sed ipsam sed.',
      'Et praesentium a iusto illo aut quia laboriosam dolore. Reprehenderit velit quis alias aperiam. Ipsam perferendis consequatur nobis sunt velit et id. Hic sunt dignissimos debitis voluptas sapiente veritatis aut sapiente.',
      'Debitis repudiandae necessitatibus modi rerum labore quaerat quia nesciunt aut. Odio est eligendi reprehenderit. Dolores iure deserunt qui itaque officia aut quia autem.',
      'Eaque et sit porro quas sint officiis quia laudantium ullam. Ipsam saepe cum odio hic. Possimus ut quasi voluptas quos incidunt ducimus rerum ut quis. Sunt nihil omnis nulla voluptatem eum molestiae rerum.',
      'Possimus non et fugit corrupti modi earum. Adipisci pariatur aut placeat aperiam ipsa eos earum. Sed nisi nihil quia culpa non hic. Sit voluptatibus fuga doloremque enim. Expedita in nam at nihil exercitationem ut nobis exercitationem aut. Ut architecto nesciunt.',
      'Voluptatem facere vel. Qui amet et suscipit. Sit nihil excepturi hic velit culpa omnis soluta in. Suscipit eveniet vitae officiis illum sed dolor rerum. Nesciunt quo molestias temporibus nisi ullam aperiam adipisci explicabo.',
      'Earum et non voluptas repellat assumenda distinctio consequatur consequatur. Harum dicta ullam. Laboriosam fugiat quo consequuntur cum saepe consequatur fuga. Minima unde unde. Quod occaecati ut porro quibusdam ab excepturi. Laudantium qui qui animi aliquam.',
      'Possimus quia dolorum minus a ut qui. Facilis optio reprehenderit esse cum.',
      'Ea nulla autem et eum voluptatem deserunt illum nemo labore. Voluptatem minus aperiam in. Odio facilis iure ut animi aut.',
      'Impedit voluptatem vitae aut. Voluptatem voluptatibus quam aut adipisci. Voluptatum commodi et libero aperiam praesentium veritatis et. Aperiam ipsa quia nesciunt voluptatem sed dignissimos. Accusantium qui labore perspiciatis earum quaerat repellendus.',
      'Quis facere sit blanditiis sit expedita blanditiis expedita totam consequatur. Quas atque eum. Nihil dicta numquam omnis. Aut aut perspiciatis placeat eius nemo dicta sint aliquid.',
      'Omnis dolore facilis ut autem molestiae et architecto id. Quia voluptatem debitis laboriosam corporis error nulla. Est et nulla non quia non. Repellat rerum ad sequi aliquid laboriosam.',
      'Magni id minus minima cupiditate voluptatem. Consequuntur asperiores beatae est quae in velit quis maiores aut.',
      'Expedita pariatur ea officiis maxime eum. Id libero excepturi veritatis ut harum non unde dolorem nihil. Eveniet rerum quia ipsa cupiditate. Sunt quidem atque eligendi est tempore magni asperiores nostrum. Sed illo eum dolorum sunt aliquid ut sint sit illo.',
      'Facilis quos ut inventore. Aut assumenda dolorem iure eos omnis ut nemo iste qui. Qui dolores adipisci minima. Cupiditate sequi repellat consequatur. Maxime id id perferendis.',
      'Autem itaque dolor. Sint provident omnis magnam pariatur. In voluptas vel voluptas eveniet est quo aut ipsam. Esse facilis quidem mollitia sunt incidunt accusantium voluptate libero et. Ullam laborum et saepe.',
      'Dicta culpa magnam. Quasi hic saepe impedit nostrum enim. Dignissimos delectus quo. Quia qui in. Autem sunt quo repellendus enim.',
      'Error molestiae omnis. Asperiores est quae ut fugit autem. Quos nobis velit placeat illum non autem rerum.',
      'Voluptate pariatur harum explicabo quia velit repellendus. Eligendi perspiciatis quasi. Nam quis quia necessitatibus veniam officiis temporibus eveniet excepturi sed.',
      'Doloremque quos quam eos nobis eveniet. Veniam quasi deleniti ipsum officia praesentium nobis vel. Illo ut accusantium voluptatem enim ex nam impedit consequuntur ipsum. Dolorem aut aut ipsa non. Vel earum voluptatibus blanditiis est velit.',
      'Fuga et corrupti quam aliquid atque. Dolore molestiae reprehenderit autem nostrum. Incidunt perferendis exercitationem officiis eius earum. Et voluptas atque consectetur molestiae minus qui.',
      'Soluta earum non odio animi aut consectetur dolore consequuntur ea. Dolores est possimus labore iste voluptatibus sint. Odio itaque voluptatem eum atque molestiae laborum et cum. Non omnis exercitationem.',
      'Et libero consequatur. Dignissimos libero omnis saepe.',
      'Ea accusantium rerum suscipit aliquid quibusdam repudiandae cum dicta. Amet exercitationem vitae aliquam culpa velit nihil. Consectetur quis est ut totam dolores. Velit omnis iure labore consequatur sed consequatur pariatur. Atque consectetur impedit ut dolorum mollitia architecto. Et fugit tempora exercitationem in enim quia et quo.',
      'Aperiam ut sint. Temporibus animi alias quae. Et est mollitia aut sit. Saepe impedit facere placeat molestiae vel sunt. Dignissimos quia consequatur quae qui laudantium. Libero non ipsam sit.',
      'Odio mollitia hic vel. Reprehenderit vel natus quae excepturi. Quia earum id voluptatem rerum. Voluptatem doloremque est quos facere tenetur illo. Omnis ut illum. Aut dolor praesentium.',
      'Est reprehenderit laborum sapiente officia laboriosam maiores qui vel. Esse sed placeat.',
      'Totam officiis sed maiores qui suscipit labore qui. Ut animi quo ut est. Deserunt distinctio labore temporibus iure asperiores non autem. Iste aut cum rerum omnis voluptatem et. Veniam sit sunt eum voluptatem ut sunt dolorem vitae. Recusandae nam exercitationem quaerat ut voluptates ut ex error.',
      'Et debitis ipsam dolor aspernatur. Sequi et sunt. Et ea rem voluptatem voluptas aut deserunt quo neque repellat. Quo id sit. Velit voluptatum repellat tempore.',
      'Non in repellat deserunt est aut animi ipsa fugit aperiam. Dignissimos sit omnis reprehenderit veniam.',
      'Sed in tempore consequuntur alias officia. Dicta est aut dolorum minus officia officiis sit voluptates consequatur. Praesentium est autem animi inventore adipisci aliquam.',
      'Cupiditate consequatur distinctio quidem repellat dignissimos. Recusandae voluptas ut. Qui saepe et velit. Voluptatem libero eum et quasi molestias dolorem ex. Quo exercitationem mollitia.',
      'Soluta incidunt voluptatem laudantium et velit repellat ad iure quibusdam. Velit error corporis iste. Nobis voluptas ut voluptatum laborum. Quo ut quis unde ipsum dolorum. Sit quam ipsum temporibus quo repudiandae.',
      'Neque ipsam nihil suscipit autem veniam consequuntur. Tenetur ut in. Rem voluptatem veritatis expedita ipsa ad. Voluptatibus nulla beatae esse nobis voluptas itaque odit. Quos ut culpa assumenda.',
      'Quisquam in debitis et mollitia odio qui aut aspernatur quasi. Alias illo culpa maiores tempora id. Rem esse quia quod mollitia aliquid ut quae recusandae voluptatibus. Non est consectetur ipsum.' ],
   images: 
    [ 'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food',
      'http://lorempixel.com/640/480/food' ],
   verified_purchase: [ true, false ],
   helpful_counter: 
    [ 200,
      5,
      70,
      16,
      200,
      132,
      127,
      193,
      177,
      85,
      165,
      123,
      28,
      27,
      108,
      157,
      10,
      156,
      99,
      41,
      116,
      90,
      53,
      164,
      133,
      61,
      182,
      26,
      183,
      26,
      14,
      116,
      177,
      13,
      99,
      161,
      91,
      107,
      12,
      63,
      163,
      56,
      15,
      50,
      58,
      128,
      153,
      134,
      104,
      40 ],
   created_at: 
    []
    };

//need to create 100 instances of the model Review. basically 100 unique items
for (var i = 1; i <=100; i++) {
  var review_instance = new Review({
    product_id: data.product_id[i],
    category: data.category[Math.floor(Math.random() * data.category.length)],
    product_name: data.product_name[i],
    product_ratings: Math.floor(Math.random() * 5) + 1,
    review: data.review[i],
    review_title: data.review_title[i],
    reviewer: data.reviewer[i],
    images: data.images[i],
    verified_purchase: data.verified_purchase[Math.floor(Math.random() * data.verified_purchase.length)],
    helpful_counter: data.helpful_counter[i],
    created_at: 'January 1, 2017'
  })
  review_instance.save((err) => {
    if (err) {
      console.log(err);
    }
    console.log('Saved yo stuff!')
  })
}




